### ISSUE TITLE
Code release date

### ISSUE THREAD

**Issue by zdyshine** [piddnad/DDColor#1]
The paper is great, I liked it a lot. Could you tell an approximate date for code realease so that I can start experimenting too? Thanks.

**Comment by piddnad** [comment]
The code does not have a specific release date yet, and we will make the source code public as soon as possible. However, you are welcome to try out the algorithm demo here in advance: [link](https://modelscope.cn/models/damo/cv_ddcolor_image-colorization/summary).

**Comment by piddnad** [comment]
Hi zdyshine, the code has been released. :)
If you find this project helpful, please feel free to leave a star ⭐️⭐️⭐️!
