### ISSUE TITLE
Extending Model Training

### ISSUE THREAD

**Issue by myeldib** [piddnad/DDColor#10]
Hi,

Thanks for your great work! I trained a model for 400,000 iterations on one dataset, and now I want to continue training for an additional 400,000 iterations using the net_g_400000.pth model. Do I just need to change the total_iter value from 400,000 to 800,000?

Thanks!

**Comment by piddnad** [comment]
Hi myeldib! Thank you for your interest in our work. 
It is ok to train for longer iterations in this way. You can also modify the 'milestones' in the 'scheduler' to further adjust the learning rate to accommodate longer training iterations.

**Comment by myeldib** [comment]
@piddnad Thanks for your answer!
