### ISSUE TITLE
How to train tiny model

### ISSUE THREAD

**Issue by junhyoung-ew** [piddnad/DDColor#16]
Thank you to share tiny model. 

When I want to train this model, can you share train method?

**Comment by piddnad** [comment]
Hi @junhyoung-ew , as stated in [Model Zoo](https://github.com/piddnad/DDColor/blob/master/MODEL_ZOO.md), the ddcolor-tiny and the ddcolor-paper share the same training scheme. 

So, you can simply modify the network_g.encoder_name in the [config file](https://github.com/piddnad/DDColor/blob/master/options/train/train_ddcolor.yml) to train the same tiny model in paper. 

Further, you may be able to obtain a better performance model than the paper by finer hyperparameter tuning and augmenting the data.
