### ISSUE TITLE
Small pretrained models?

### ISSUE THREAD

**Issue by qiankl** [piddnad/DDColor#2]
Any plan to release small pretrained models?

**Comment by piddnad** [comment]
由于公司政策，预训练模型发布可能比预期时间要长。一旦有发布，我会第一时间在 Readme 中更新，感谢你的关注！

**Comment by piddnad** [comment]
Due to company policy, the release of pretrained models may take longer than expected. I will update READEME as soon as there is a release plan, thank you for your attention! :)

**Comment by delldu** [comment]
We are looking forward, many thanks !

**Comment by piddnad** [comment]
Hi @qiankl @delldu , I'm excited to share that we've officially released DDColor-tiny, the most lightweight version of our model! We appreciate your patience and warmly invite you to try out the new release :)

**Comment by qiankl** [comment]
@piddnad Thanks for your work!
