### ISSUE TITLE
How to fine-tune existing model?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [piddnad/DDColor#24]

**Comment by piddnad** [comment]
Hi, you can refer to https://github.com/piddnad/DDColor/issues/3#issuecomment-1698573748  and set pretrain_network_g as an existing model in the configuration file.

**Comment by mycomedico** [comment]
Do i need both the black and white and color images?  or does the training automatically generate black and white images?  do i need to specify seperate folders for the images if i need to include both?    my images have resolution of 720height x 992 width.  is this the correct format to specify that:      gt_size: [720, 992]

**Comment by piddnad** [comment]
> Do i need both the black and white and color images? or does the training automatically generate black and white images? do i need to specify seperate folders for the images if i need to include both? my images have resolution of 720height x 992 width. is this the correct format to specify that: gt_size: [720, 992]

1. Only color images are needed. During training, color images will automatically converted to black and white images. So just set your color image path list file in "meta_info_file" (e.g. 'data_list/imagenet.txt'). 
2. No, there is no need to change "gt_size". "gt_size" represents the resolution of GT samples and 256 is usually sufficient. When training, dataloader will automatically resize the input to the this size (see [here](https://github.com/piddnad/DDColor/blob/5a764a218288ad059b5bf281fca11847c8838fe3/basicsr/data/lab_dataset.py#L75)) .

Hope this helps!
