### ISSUE TITLE
National Flags Colorization

### ISSUE THREAD

**Issue by skysbird** [piddnad/DDColor#28]
Is there a way to make the coloring of the national flag more precise?

![image](https://github.com/piddnad/DDColor/assets/38487/6396f45e-b605-43e8-b92f-7ae50079258c)

**Comment by piddnad** [comment]
The model was trained on academic datasets (ImageNet & COCO), so some specific objects with fixed colors, such as flags, may not have been seen.

Anyway, I believe that fine-tuning the model using images with national flags can solve this problem very well.
