### ISSUE TITLE
How to train on my own dataset?

### ISSUE THREAD

**Issue by Badw0lf613** [piddnad/DDColor#3]
Sorry to bother. I'm trying to train DDColor on my own dataset. Is there any training scripts? By the way, how to prepare and organize my dataset?

**Comment by Badw0lf613** [comment]
I see the training scripts and files, that is basicsr/train.py.

**Comment by piddnad** [comment]
抱歉打扰了。我正在尝试在自己的数据集上训练DDColor。有训练脚本吗？顺便问一下，如何准备和组织我的数据集？

**Comment by piddnad** [comment]
Sure! It's easy to train DDColor on your own dataset.

First, you need to organize your dataset by placing the images in a folder, and then use [data_list/get_meta_file.py](https://github.com/piddnad/DDColor/blob/master/data_list/get_meta_file.py) to generate a datalist file.

Next, you need to modify the path to the training dataset's metadata file in the [training config](https://github.com/piddnad/DDColor/blob/1a190e235e7175a3e4381e2511297116b1fb1112/options/train/train_ddcolor.yml#L15).

Finally, as you mentioned, you can use basicsr/train.py for training. The command format can be found in [scripts/train.sh](https://github.com/piddnad/DDColor/blob/master/scripts/train.sh).

Hope this answer has addressed your question.
