### ISSUE TITLE
DDColor ONNX

### ISSUE THREAD

**Issue by instant-high** [piddnad/DDColor#31]
Thanks for your great work, results on images even better than deoldify.

I've converted the models to onnx for more simple installation...

**Comment by piddnad** [comment]
Thank you for your interest in our work. If you want to share your changes, feel free to submit a PR!

**Comment by instant-high** [comment]
@piddnad 
sorry for the delay. I already had made a small repository containing onnx inference code and onnx conversion code.
I'm not shure if I can publish the onnx converted model(s).

**Comment by piddnad** [comment]
Hey @instant-high , that's okay! If you want to share your implementation, you can also add your repository link to the README and launch a PR at any time. :)
