### ISSUE TITLE
Coloring video will cause flickering

### ISSUE THREAD

**Issue by liangbaikaizzzZZZ** [piddnad/DDColor#35]
When I turn a black-and-white video into a colored one, the video flickers. Sometimes, there is a big difference in color between adjacent frames, which causes the video to flicker. Is there any way to make the video more stable?

**Comment by piddnad** [comment]
Hi @liangbaikaizzzZZZ ! Since DDColor is not specifically trained for video colorization, so it is normal  for sub-optimal results. However, you can retrain a model and use early-step checkpoints for a more stable video colorization, please refer to https://github.com/piddnad/DDColor/issues/4.
