### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by weixin6666** [piddnad/DDColor#36]
Blogger hello, would like to ask a question, when I run the train.py script, encountered FileNotFoundError: [Errno 2] No such file or directory: 'data_list/imagenet.txt' this problem. I have imagenet.txt in the data_list file, but it keeps saying it can't find it. And this imagenet.txt is generated when you run data_list/get_meta_file.py (I'm afraid I got this wrong)

**Comment by weixin6666** [comment]
In train_ddcolor.yml, the absolute path to imagenet.txt was changed to not display this error, but the display could not find imagenet_val_5k.txt. this file seems to have not been generated before running get_meta_file.py

**Comment by piddnad** [comment]
Sorry, I didn't get it. 

data_list/get_meta_file.py is a sample script for generating the data list file needed for training. Before starting the training, you need to ensure that all data list files in the training configuration (train_ddcolor.yml) have been successfully generated.

**Comment by weixin6666** [comment]
But I don't know where to generate imagenet_val_5k.txt, I don't see the relevant code in this script (data_list/get_meta_file.py ), only see the code to produce imagenet.txt

**Comment by piddnad** [comment]
Hi, @weixin6666 , imagenet_val_5k is actually the first 5,000 images in imageney validation set, you can edit the script to generate it.
