### ISSUE TITLE
Reducing flickering artifacts (temporal inconsistency)

### ISSUE THREAD

**Issue by myeldib** [piddnad/DDColor#4]
Hi,

I truly appreciate your commendation for the work! Currently, I'm in the process of training DDCololr using a dataset that I've curated. Specifically, I've employed 1 million images for the training process, spanning across 400,000 iterations. However, I've encountered an issue where certain images exhibit flickering artifacts (unpleasant red artifacts on shadow), which can be attributed to temporal inconsistency. This concern becomes more pronounced when applying colorization to videos. To provide you with a visual understanding, I've attached images that showcase this artifact, with the affected areas circled in white.

I'm interested in exploring potential adjustments to the training parameters to mitigate this impact. Your insights on which parameters could be modified to address this issue would be greatly appreciated
![3](https://github.com/piddnad/DDColor/assets/63010437/a8fafa20-db4d-4792-a697-9f6c39697470)
![2](https://github.com/piddnad/DDColor/assets/63010437/58549669-8fa3-46aa-93b6-50c3443ad3db)
![1](https://github.com/piddnad/DDColor/assets/63010437/13a92067-3282-4bed-916a-d5883c9347b3)

**Comment by piddnad** [comment]
Hello myeldib, thank you for your interest in our work.

When using DDColor for video colorization, we recommend using checkpoints with fewer iteration steps. This can help reduce color flickering between video frames. Additionally, try training without colorfulness loss (comment [these three lines](https://github.com/piddnad/DDColor/blob/1a190e235e7175a3e4381e2511297116b1fb1112/options/train/train_ddcolor.yml#L132-L134) may help mitigate the issue of red artifacts in the generated images. Colorfulness loss encourages more "colorful" results but sometimes leads to the generation of unpleasant color blocks.

I hope this information is helpful to you.

**Comment by piddnad** [comment]
Hello myeldib, thank you for your interest in our work.

When using DDColor for video colorization, we recommend using checkpoints with fewer iteration steps. This can help reduce color flickering between video frames. 

Additionally, try training without colorfulness loss (comment [these three lines](https://github.com/piddnad/DDColor/blob/1a190e235e7175a3e4381e2511297116b1fb1112/options/train/train_ddcolor.yml#L132-L134) may help mitigate the issue of red artifacts in the generated images. Colorfulness loss encourages more "colorful" results but sometimes leads to the generation of unpleasant color blocks.

I hope this information is helpful to you.

**Comment by piddnad** [comment]
Hello myeldib, thank you for your interest in our work.

When using DDColor for video colorization, we recommend using checkpoints with fewer iteration steps. This can help reduce color flickering between video frames.

Additionally, try training without colorfulness loss (comment [these three lines](https://github.com/piddnad/DDColor/blob/1a190e235e7175a3e4381e2511297116b1fb1112/options/train/train_ddcolor.yml#L132-L134)) may help mitigate the issue of red artifacts in the generated images. Colorfulness loss encourages more "colorful" results but sometimes leads to the generation of unpleasant color blocks.

I hope this information is helpful to you.

**Comment by myeldib** [comment]
@piddnad , I appreciate your swift response. Could you kindly guide me to the specific configuration parameters that I need to adjust in order to utilize checkpoints with a reduced number of iteration steps?
Are we talking about this parameter?
[milestones](https://github.com/piddnad/DDColor/blob/1a190e235e7175a3e4381e2511297116b1fb1112/options/train/train_ddcolor.yml#L101C5-L101C15)

**Comment by myeldib** [comment]
Thanks again for answering my questions and the amazing work!

**Comment by shubhamgupto** [comment]
Hey @piddnad thank you for the guide! I am curious to know whether we can just finetune the released weights such as `ddcolor-tiny.pth` without colorfulness loss. The current models do perform well OOD and i dont want to lose that.

Let me know if finetuning for video colorization makes sense. 

Thanks again
