### ISSUE TITLE
Basicsr issue

### ISSUE THREAD

**Issue by Xia-zx** [piddnad/DDColor#41]
I am trying to train the model on custom dataset,but I meet this problem.
My version is: CUDA==11.7，torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2, basicsr==1.4.2
What version of torch and basicsr should I install?
Thank you!
<img width="572" alt="微信图片_20240613155202" src="https://github.com/piddnad/DDColor/assets/40895291/d1e27540-7d99-4939-9b5d-af04a1381261">
<img width="728" alt="微信图片_20240613155253" src="https://github.com/piddnad/DDColor/assets/40895291/6fd84a44-8ae0-4b0a-87ce-12019c85322c">

**Comment by piddnad** [comment]
The problem is usually because that basicsr is not properly registered. You can try run 'python3 setup.py develop'.

**Comment by piddnad** [comment]
Hi @Xia-zx , this issue is usually because the basicsr were not registered correctly. You can try running 'python3 setup.py develop' in the ddcolor directory, and hopefully this will help.

**Comment by Xia-zx** [comment]
> Hi @Xia-zx , this issue is usually because the basicsr were not registered correctly. You can try running `python3 setup.py develop` in the ddcolor directory, and hopefully this will help.

After running python3 setup.py develop,which install some package which is dependencies for basicsr==1.3.4.6,like torch==2.2.0
but My CUDA==11.7,there is another error
I think the only way to solve this is change the basicsr version and torch version to match my CUDA
Does the lower version of basicsr will work ?
thank you!
<img width="744" alt="微信图片_20240613165912" src="https://github.com/piddnad/DDColor/assets/40895291/00ceb8a9-3a4a-4ecd-bdb6-21661d960cb2">

**Comment by piddnad** [comment]
In this case, I think you can comment out the torch version in `requirements.txt` before running `python3 setup.py develop`. This will prevent torch from being reinstalled.

**Comment by ChuRuaNh0** [comment]
@piddnad 
I tried install setup,py but register dataset still errror
![image](https://github.com/piddnad/DDColor/assets/83876298/ab09af37-c3b7-4eb5-9295-f044f5063a68)

**Comment by piddnad** [comment]
Hi @Xia-zx , I've just updated the installation guide in the README. You can check it out [here](https://github.com/piddnad/DDColor?tab=readme-ov-file#installation-with-conda-recommended). 

I tested the new installation steps myself, and they worked well for me. Hope this will solve your problem. Please give it a try!

**Comment by Xia-zx** [comment]
> Hi @Xia-zx , I've just updated the installation guide in the README. You can check it out [here](https://github.com/piddnad/DDColor?tab=readme-ov-file#installation-with-conda-recommended).
> 
> I tested the new installation steps myself, and they worked well for me. Hope this will solve your problem. Please give it a try!

Thank you for your reply
I solved the problem of bisicsr,but I meet some NCCL problem. I've never used NCCL. Do you know the reason for the error in the picture below
Thank you again
![Uploading 微信图片_20240618115520.png…]()

**Comment by Xia-zx** [comment]
> Hi @Xia-zx , I've just updated the installation guide in the README. You can check it out [here](https://github.com/piddnad/DDColor?tab=readme-ov-file#installation-with-conda-recommended).
> 
> I tested the new installation steps myself, and they worked well for me. Hope this will solve your problem. Please give it a try!

I have solved the problem，thank you for your reply
