### ISSUE TITLE
Incredible work, unfortunately there is a color instability in the colorization video. 

### ISSUE THREAD

**Issue by nass2020** [piddnad/DDColor#7]
Hello congratulations for this work, it's really incredible, is there a way to fix the color instability in the video colorization for objects that move such as cars and people walking?  Are there any modifications to be made? Where to train the model with specific modifications? Thank you for your reply

**Comment by piddnad** [comment]
Thank you for your interest in our work.

When using DDColor for video colorization, we recommend using checkpoints with fewer iteration steps. This can help reduce color flickering between video frames. Additionally, try training without colorfulness loss (comment [these three lines](https://github.com/piddnad/DDColor/blob/1a190e235e7175a3e4381e2511297116b1fb1112/options/train/train_ddcolor.yml#L132-L134)) may also help.

Note that DDColor is not specifically trained for video colorization, so there may be some sub-optimal results in terms of color consistency in videos.

**Comment by nass2020** [comment]
Thank you very much for your reply and congratulations again on your work, I hope you do something for the colorization video soon, greetings

**Comment by piddnad** [comment]
Thanks, we will update as soon as there is any new progress :)

**Comment by nass2020** [comment]
Thank you very much, I wish you good luck!
