### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by aliosmanbaykus** [piddnad/DDColor#8]
Hi, I am trying to train the model on custom dataset but I'm taking that error. Can you explain more how should I prepare train_ddcolor.yaml.
<img width="500" alt="image" src="https://github.com/piddnad/DDColor/assets/72699390/af46bec9-d7b2-4bd5-a4c2-dbc7d5f04f42">
This is train_ddcolor.yaml file that I use.
![output-onlineyamltools (2)](https://github.com/piddnad/DDColor/assets/72699390/c74f6241-1ae2-43cc-8675-ff7b8cd13993)

**Comment by piddnad** [comment]
This error is usually caused by basicsr not being installed properly, try using python3.8 + torch1.7.1 and execute `python3 setup.py develop` to solve this problem.

**Comment by aliosmanbaykus** [comment]
Thank you!
